### ISSUE TITLE
[1.14.4] Server-Console being spammed with "Event Fired" !

### ISSUE THREAD

**Issue by Gbergz** [Wavebrother/EnderEnhancement#3]
----------------------------
Having an issue with the Console being spammed by "Event Fired" it's caused by some block i think.

Checking the logs reveals that it's from this mod. The "Event Fired" message is now turned into
"[Server thread/DEBUG] [wavebrother.enderEnhancement.EnderEnhancement/]: Harvest"
I think it is most definitely that. 

Because this is what the Console looks like [[ GYAZO ]](https://gist.github.com/Gbergz/e649dc09c6fc579e6efbe9e3ecf35490) 

And this is what the Debug.Log of the console looks like: [[ GYAZO ]](https://gist.github.com/Gbergz/e52a31ed313c61f0a704aea5422911ef)

It translated into the cause.

----------------------------

Forge Version: 28.1.107
Mod-Version: 1.14.4-1.0.3.0
Minecraft-Version: 1.14.4

Hope this can be solved. As it makes it the server-console unbearable to look at or moderate.

----------------------------

**Comment by Wavebrother** [comment]
Oh. Apparently I didn't remove that from testing. Ill get an update out ASAP

Edit: It has been fixed in 1.0.3.1.
