### ISSUE TITLE
Enderman Agitator issues

### ISSUE THREAD

**Issue by SissyTrashQueen** [Wavebrother/EnderEnhancement#4]
First issue: Any tier of enderman agitator angers the enderman even if you're on creative mode.

Different issue:
~~The idea to calm mobs through the agitator is expected to be a chance that depends on the tier, right? The lower the tier, the lower the chance?~~
If the answer is yes: The pigman agitator, regardless of tier, always calms the pigmen.
Yet the enderman agitator, on lower tiers, works a lot more _randomly_

I thought that tiers had to do with chance, but now I've realized that tiers change the distance it affects mobs. **But the calming mode doesn't seem to affect mobs on the same range horizontally, one block above/below me**. That's why the enderman agitator seemed like it is more random on lower tiers, due to it having one more tier (lower) than the pigman one and calming mode isn't affecting all mobs around me.

Also a crash happened
[Extract from latest.log](https://hastebin.com/tezarucuyo.pl)
I was messing around with the agitator, picking it up and dropping it right away. ~~It seems forge couldn't handle it but I'm no expert about mod dev~~

Nevermind, it happened _again_: [Crash report](https://hastebin.com/yegodewoni.pl)

**Comment by Wavebrother** [comment]
> First issue: Any tier of enderman agitator angers the enderman even if you're on creative mode.

I fixed it.

> I was messing around with the agitator, picking it up and dropping it right away

I'm guessing you were dropping the pigman agitator with the enderman agitator, and then were hit by an enderman.
If so, I found the issue and fixed it.

> I thought that tiers had to do with chance, but now I've realized that tiers change the distance it affects mobs.

Do you think that a chance would work better? I just implemented it the best way I could, but I'm bad at ideas. I am very open to suggestions.

> But the calming mode doesn't seem to affect mobs on the same range horizontally, one block above/below me.

Are you saying that the lower tiers don't work if the enderman is above or below you, or that the range seems to be lower if they are above you?

**Comment by SissyTrashQueen** [comment]
> Do you think that a chance would work better? I just implemented it the best way I could, but I'm bad at ideas. I am very open to suggestions.

Since it will be used in mob farms, I think it's very well implemented. I simply had a different first thought.

> > But the calming mode doesn't seem to affect mobs on the same range horizontally, one block above/below me.
> 
> Are you saying that the lower tiers don't work if the enderman is above or below you, or that the range seems to be lower if they are above you?

A video might explain it better:
https://imgur.com/a/zqN7pHe

First I filled the place of endermen, I get to a safe spot and activate the Agitator, so all the endermen come to me. Then I deactivate the item but some endermen are still angered. I fell to the same block level as them which finally makes every enderman passive again.
(the red skull above them is the mod [Enemyz](https://www.curseforge.com/minecraft/mc-mods/enemyz) and it tells you visually which mobs are angered at you)

EDIT:
And two videos more: https://imgur.com/a/3N6y0G7
First one shows that doesn't matter if your block is one below (or one above like the video before showed), the calming mode doesn't affect the enderman, you must be standing at the same block level as them.

And the second video shows another bug: **If you've angered the enderman with the agitator** and **calmed it afterwards**, drop the agitator and the enderman won't anger through "vanilla means" (looking and/or hitting them).

**Comment by Wavebrother** [comment]
> Then I deactivate the item but some endermen are still angered. I fell to the same block level as them which finally makes every enderman passive again.

~~This is because some of the endermen were outside of the range of the agitator when you activated it.~~ I don't know why it pacifies at first. I didn't want to check if any endermen were angry every tick, so I instead check whenever you are hit by an enderman.

> If you've angered the enderman with the agitator and calmed it afterwards, drop the agitator and the enderman won't anger through "vanilla means" (looking and/or hitting them).

I will check on whats going on here.

I can't seem to replicate this or find any reason why it would be doing this unless you had another agitator in your inventory.

**Comment by Wavebrother** [comment]
I am going to close this. If you are still having issues reopen it.
