### ISSUE TITLE
Teleporter durability and some nitpicks

### ISSUE THREAD

**Issue by SissyTrashQueen** [Wavebrother/EnderEnhancement#5]
Is the teleporter supposed to be damaged on use? If yes, it isn't being damaged by teleporting.
![2020-03-25_19 47 41](https://user-images.githubusercontent.com/55768134/77593637-46035600-6ed3-11ea-83d3-444e01089888.png)
On a little different matter, I give you an idea for it: the teleporter instead of getting durability damage, could consume one pearl of the same tier level for each teleport.

Also, is this mod responsible for the damage I take each time I throw  a ender pearl to teleport?

And finally, on the netherenhancement-common.toml there's a line that reads "#Ender Armor Settings"

**Comment by Wavebrother** [comment]
What version are you on?

> Is the teleporter supposed to be damaged on use? If yes, it isn't being damaged by teleporting.

It is supposed to be damaged on use. I will check on why this is happening.

> On a little different matter, I give you an idea for it: the teleporter instead of getting durability damage, could consume one pearl of the same tier level for each teleport.

That is a very good idea! I am going to get to work on this when I have some spare time.

> Also, is this mod responsible for the damage I take each time I throw a ender pearl to teleport?

I don't believe so. I believe that is vanilla behavior, but I will check on it.

> And finally, on the netherenhancement-common.toml there's a line that reads "#Ender Armor Settings"

That.. is not supposed to be there. Thanks for letting me know.

**Comment by SissyTrashQueen** [comment]
> What version are you on?
>
EnderEnhancement-1.15.2-1.0.3.3

> That is a very good idea! I am going to get to work on this when I have some spare time.
>
Cool! :)

> I don't believe so. I believe that is vanilla behavior, but I will check on it.
>
"Using an ender pearl deals 5 damage to the user"  It's been so long since I used a pearl, and I didn't thought of it being vanilla behaviour lol, forget that I reported that

**Comment by Wavebrother** [comment]
Ill get these changes on curse tomorrow night. I'm working on some other features that I want to get in the update.
