### ISSUE TITLE
Crafting recipe problem

### ISSUE THREAD

**Issue by Thexpire** [Wavebrother/EnderEnhancement#6]
All the stuff from the mod has been added but i'm not able to craft it.The recipes don't work or something
1.12.2 version
Help please

**Comment by Wavebrother** [comment]
I don't see why there would be any issue with recipes, as there were no changes to recipes between 1.12 and 1.14. I will see if I can find out whats going on.

**Comment by Wavebrother** [comment]
Sorry I haven't update you! School has started back up, so I am very busy. I have not been able to find a reasons recipes would not be working. If you have JEI, do they show up there?
