### ISSUE TITLE
CurseForge description should mention it's for Fabric

### ISSUE THREAD

**Issue by ghost** [Wavebrother/EnderEnhancement#7]
Fabric users won't see it and people making Forge packs will mistakenly download it.

**Comment by Wavebrother** [comment]
I would do that if it was made for Fabric, but it's not. It's made for Forge.

**Comment by ghost** [comment]
Sorry, threw together a bunch of mods in Forge and a few came up as Fabric. EnderEnhancement had a different error. I'll do a new issue.
